###
# POST Login Users Request Test
###
      
@auth = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJlbWFpbCI6InNoZWVyd2luQGV4YW1wbGV0ZXN0LmNvbSIsImlhdCI6MTY5OTY4MTM2NywiZXhwIjoxNjk5Njg0OTY3fQ.oaAYHT98_zv_3lf6MaODBT404pv21BRgoD_R7bHW_d0
# Request
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "sheerwin@exampletest.com",
  "password": "Hana123"
}


###
# GET Users Request Test
###

# Request
GET http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{auth}}

###
# GET User by ID Request Test
###

@id = 6

# Request
GET http://localhost:3000/api/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{auth}}
###
# POST User Request Test
###

# Request
POST http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "name": "Sheerwin",
  "phoneNumber": "012345678",
  "password": "Hana123",
  "email": "sheerwin@exampletest.com",
  "enabled": 1
}

###
# PUT User Request Test
###

# Request
PUT http://localhost:3000/api/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "name": "Updated Sheerwin",
  "phoneNumber": "987-654-3210",
  "password": "updatedpassword4567",
  "email": "sheerwin@examples9.com",
  "enabled": 0
}

###
# DELETE User Request Test
###

# Request
DELETE http://localhost:3000/api/users/{{id}}
Content-Type: application/json

###
# Enable User Request Test
###
# Request
PATCH http://localhost:3000/api/users/{{id}}/enable
Content-Type: application/json
Authorization: Bearer {{auth}}

###
# Disable User Request Test
###

# Request
PATCH http://localhost:3000/api/users/{{id}}/disable
Content-Type: application/json
Authorization: Bearer {{auth}}