"use client";
import "./globals.css";
// import type { Metadata } from 'next'
import { useAmp } from "next/amp";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import Loader from "../../components/loader/loader";
import Footer from "../../components/footer/footer";
import { NavBar } from "../../components/header/header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  });

  return (
    <html lang="en">
      <body>
        <div>
          {loading ? (
            // Display loading screen first if webpage still building
            <Loader />
          ) : (
            <div>
              <NavBar />
              <div>{children}</div>
              <Footer />
            </div>
          )}
        </div>
      </body>
    </html>
  );
}
