###
# GET Request Test
###
@id = 1
@base_url = "http://localhost:3000/api/recruitments"

# Request
GET http://localhost:3000/api/recruitment
Content-Type: application/json

###
# End of GET ALL Request Test
###

###
# GET BY ID Request Test
###

# Request
GET http://localhost:3000/api/recruitments/{{id}}
Content-Type: application/json

###
# POST Request Test
###

# Request
POST http://localhost:3000/api/recruitment
Content-Type: application/json

{
  "position": "Software Engineer",
  "description": "Join our team!",
  "requirement": "Experience with web development",
  "postedDate": "2023-10-13"
}

